# use the correct architecture (x-86_64 / arm64)
# any external packages can be installed using yum
FROM public.ecr.aws/lambda/python:3.8-x86_64

# apparently using COPY will make the program not realise app is a module.
ADD app app

# install packages for opencv operations
RUN yum -y install mesa-libGL libsndfile

COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

# All cache directory must be set to /tmp (lambda tmp directory)
ENV NUMBA_CACHE_DIR=/tmp
ENV MPLCONFIGDIR=/tmp

# project_folder.py_file.mangum_object_name
CMD ["api.main.handler"]